apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "postgres-db.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "postgres-db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "postgres-db.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "postgres-db.name" . }}
    spec:
      serviceAccountName: {{ include "postgres-db.fullname" . }}
      containers:
        - name: postgres-db
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "postgres-db.fullname" . }}
            - secretRef:
                name: {{ include "postgres-db.fullname" . }}
          volumeMounts:
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: init-script
          configMap:
            name: {{ include "postgres-db.fullname" . }}-init
