replicaCount: 2

namespace:
  create: true
  name: customer-services

image:
  repository: customer-register
  tag: latest
  pullPolicy: IfNotPresent

service:
  # cluster ip is for internal communication within the cluster
  # we will have to use port-forward for local testing or an ingress or a load balancer for external access
  type: ClusterIP
  port: 3011

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "256Mi"

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

db:
  host: helm-project-postgres
  port: 5432
  name: helm_project
  user: postgres

secrets:
  dbPassword: mysecretpassword
