apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "register-customer.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "register-customer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "register-customer.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "register-customer.name" . }}
    spec:
      serviceAccountName: {{ include "register-customer.fullname" . }}
      containers:
        - name: register-customer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: {{ include "register-customer.fullname" . }}
            - secretRef:
                name: {{ include "register-customer.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
