apiVersion: v1
kind: Service
metadata:
  name: {{ include "register-customer.fullname" . }}
  namespace: {{ .Values.namespace.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "register-customer.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
